version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Download and install tflint
          command: |
            wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
      - run:
          name: Lint the terraform code
          command: ./tflint --deep --aws-region us-east-1
      - run:
          name: Run terraform init
          command: terraform init -input=false tests/integration
      - run:
          name: Run terraform plan
          command: terraform plan -out=tfplan -input=false
      - persist_to_workspace:
          root: .
          paths:
            - tfplan
